### ISSUE TITLE
Jon Moeller's feedback

### ISSUE THREAD

**Issue by tchoi8** [tchoi8/handmadecomputer#1]
- Short lines of text that's between watercolor texts are distracting. Either render as hand drawn or edit out to appendix. when the style changes drastically, reader is taken out of the world of the piece 
- It's not clear who's voice it is. Maybe define the narrator from the beginning? Is it Taeyoon? The computer person? 
- When I talk about representation, visualize it by repeating parts of the drawing? scale - like zooming out or zooming in to the microchip? 
- TY's skill is humanizing digital things, maybe focus on that?
- 1 and 0 are clone of itself
- why is the chapter two titled interface? actually don't talk about interface so much
- 0 and 1 is like voltage level, machine code, it's how we interface with objects
- unreal- symbolic in some way 
- jump between the chapters? define it more or bridge? 

Part three starts to be very technical and more difficult to follow 
- other than having hands coming out of logic gates and has handshake as signal, how about only outputs has hands, and it's either thumbs up or thumbs down? 
- when introducing the logics, get rid of buffer. its more confusing?
- maybe get rid of ven diagrams, or logic symbols? too much information in this section.
- TTL needs to be defined 

Part four
- Where is the dumpling shop? is it called cpu dumpling? 
- Train track metaphor
- Assembly, opcode - ALU/ operands - mux/register 
- Binary again  opcode and operand comes in to the control unit, which decodes it 

Jon's comment was focusing on the reader's experience. There are design decisions that can help readers greatly. Also, on the technical side, it maybe unnecessary to explain everything.

**Comment by hxrts** [comment]
Closing this, I think we've addressed pretty much everything that isn't in other comments.
