### ISSUE TITLE
Jonathan Dahan's feedback

### ISSUE THREAD

**Issue by jedahan** [tchoi8/handmadecomputer#2]
I'm posting this in hopes that others can have discussions around it...
## Introduction / Chapter 1

I **love** the sun/no sun analogy...I smiled when it was introduced.

The intro makes me want to hear _how_ your proposal that abstraction and repetition allows for in-between states. If this is explored in more depth later, awesome. Maybe hint to the reader that we will get to that point sometime in the future. Either way, I am eager to read more.

**Comment by jedahan** [comment]
# Interface

Beautiful painting of a laptop - the empty space let's me think of it as an idea, not just a painting of a laptop.

I think the "Each one comes to be a whole one to me" is where I started to get a bit confused. But I am curious enough to see where that thought goes enough to just get on to the next chapter, though its not clear where it will lead. Plus I wanna see more drawings...

**Comment by jedahan** [comment]
# Binary

For the inverter, mayble labeling input as A and output as B would be nice. I am not sure what A and B represent for the venn diagrams for the inverter. But for some reason, I have a really hard time with Venn Diagrams represending truth tables, i'm sure you remember ;)

"The second basic computing operation is data storage" ... I searched the document for 'basic computing operation'...maybe it is implied, but it would be nice if earlier in the document, you where explicit in stating 'the first basic computing operation is ___'...whatever the ___ should be.

"where an input **set**" maybe "where an input we are going to label **set**"

You first explain how a latch operates, but not exactly why this is memory. Maybe an analogy would help here.

The codepen is unfinished? It only outputs "blink ${seconds}" when i turn the knob. Love the idea of interactive drawing...

**Comment by jedahan** [comment]
# Dumpling

"Von Neumann's innovation with this architecture was to allow data and memory to be treated interchangeably" ... did we establish that data and memory were different before this? I don't remember... or is this not that important.

Also, as an aside / footnote somewhere (no idea if it should be this chapter or some other one), maybe mentioning that there is no difference between code and data...its all just numbers in memory we define. Maybe during a programming language chapter and how lisp is interesting.

I don't know why, but I started skimming after reading about the finite state machine. I was imagining what it was doing, and really wanted to play with one immediately. Now I want to model one up in kicad/fritzing and make my own :D

**Comment by jedahan** [comment]
# RAMcity

[Not sure of reserving the spot is necessary or , not sure if I understand what it means. deleting that part for now. ] // I think this more has to do with operating systems than hardware. It depends on what your focus is. OS and programming languages and memory management is interesting, so maybe as a footnote mention "if you want to extend the metaphor and think about operating systems, we actually reserve memory with functions like malloc() ... maybe there is a ticket system here..."

Definitely think mux/demux could use a bit more work. Not sure if this is helpful, but the NES controller is just a shift register...

Beautiful ending.

**Comment by jedahan** [comment]
The journey is great. There a lot to grab onto, without being like "After you are done with this book, you will have built a computer". It reminds me a tiny bit like _why's poignant guide, though that is much more strict in its goals.

I hope some of this feedback is helpful

**Comment by hxrts** [comment]
Thanks so much for your comments Jonathan. Where you've marked confusing areas is particularly helpful. That's what I'm trying to focus on most while editing, rounding out some of these so readers don't get hung up. If you think of anything else, please don't hesitate. Your comments are very welcome.

**Comment by tchoi8** [comment]
thanks so much Jonathan. Super helpful.

**Comment by hxrts** [comment]
Consolidating comments for my own sanity. I've addressed a few of these issues, still have several to go. Working mostly in a gdoc for Rhizome's sake, but will back-edit github for posterity.
