### ISSUE TITLE
Overall and Introduction 

### ISSUE THREAD

**Issue by tchoi8** [tchoi8/handmadecomputer#6]
After almost a month of hiatus from the project, I'm diving deep back in to the project. Thanks to many great friends who gave thoughtful feedback, I think we can now step forward toward completion. 

Story
- How to balance the technical description, narrative consistency and artistic voice? If the piece is a facet to many interesting perspective to computation, how to prevent over explaining or sticking in the details? On the other hand, how to avoid skipping through critical information that the reader needs to comprehend and enjoy the piece?  
- The piece is missing an ending, resolution of anything. The big question is what kind of computer do I want to build? some leads will make the reading more satisfactory. 
- The unclear voice of narrator: who is the narrator? if it is taeyoon ? if so. would it help for him to be a stick figure? or mr transistor? i guess it depends on the ideal reader for this piece. it's not really meant for young audience, so making it any more cuter won't really help...

Aesthetics + style
- Consistency of visual style can help readers concentrate on the contents. Small adjustment, of making each chapter look in similar style can help. Especially typed words between the images are big distraction. 
- at the moment, the images are applied without resizing- this is the time to begin editing images/ mocking up.
- integrating video clips as gif would be easier to share more contents passively
- interactive elements need to be highlighted as interactive 

Introduction
- The very first image "This is a story about..." is color. use original?
- I do highlight that "it's possible through abstraction and repetition" but don't follow up with how those actually work in the following chapters. Maybe connect the contents (like how transistors are used to make logic gates, dumpling stores and etc) to these two concepts as much as possible? 
- Dahan "The intro makes me want to hear how your proposal that abstraction and repetition allows for in-between states."
- "The last computers maybe human as well" is confusing. already feels like an ending. maybe save this for the final chapter? my vision of computers as organically analog, can be the 'human' aspect of computers. 
- Final image, the three figures that are dancing together, Laptop person, Human person, Transistor person - are they different characters? if so, can they have different voice?, for example their voices are rendered differently? or each chapter is clearly narrated by different figure? 
  ~~\- Kyle "Smart watch vs Data center" comparison might not be effective~~
- The color gradation in the first chapter seems to work well, catching reader's attention. New contents for the chapter one needs to be rendered in the same style. The last few drawings, done in black and white, look out of place.
-  I wonder if it's realistic to code the background to change color from complete black to white over time. I think that works well with the idea of analog transitions, the world is not binary and there are numbers between zero and one. 
  ~~\-  Still not sure what to do with all the references.~~

**Comment by hxrts** [comment]
- wow, lots of edits in the first chapter. I like it, there's a few grammatical things I'll have to do in photoshop.
- Keeping a closer eye on keeping a consistent voice would be great. I've been making changes here and there to keep the text in a more narrative style. I'm ok with the tonal unity, I definitely reads as your voice all the way through but keeping a consistent audience in mind could be a nice reference point. Perhaps and SFPC student on day-1, or someone who knows very basic programming but wants to know more about how the computer underneath works.
- Don't worry about references at this point. We can put them in a collapsable area, or at the end. Just try to keep them up to date and formatted with some consistency and we can find a good strategy when we see it on the website.
- Doing gradated background could be really easy if it's a static gradient, just a simple styled html block.
- I agree to an extent with Kyle's suggestion to end the piece on where HC is going, but I think my take is slightly different. Here's my general notion of how the whole story flows so we can talk about the piece as a whole:
  - Intro: origin of computing (politics & history) then set up for overarching concepts + why it's important to build a computer
  - Interface: contemporary state of computing, the computer's failure as a liberatory technology, commodification & movement toward obfuscation THUS we can build a computer to recover latent democratizing potential. begin with abstraction & repetition.
  - 0&1: binary -> transistors -> gates `this section should reinforce your abstraction and repetition premise and evoke the historical idealism of early computing` explain the 3 components required to build a working HC aka (turing-equivalent machine)[https://en.wikipedia.org/wiki/Random-access_machine](1) clock (2) symbol map / arithmetic logic (3) RAM
  - CPU dumpling shop: break from romanticizing with the contrasting militarization story. use von Neumann as segue into CPU, the dumpling metaphor / interlude brings you back to repetition and abstraction which lets you draw the similarities between digital computation : human computation :: circuits : cities
  - RAM city: the reader is now sold on the repetition and abstraction idea, so you can tie up the only remaining computer component, RAM, while starting to build out your city metaphor with some poetic license. personally, the "where does HC lead?" question is not so much about what kind of computer do you want to build, but what kind of world does HC open up to people? You suggest this beautifully aware and honest means of interfacing with our technological surroundings, how does this performance change our relationship to the space around us and to each other? what does this mode of interaction look like if scaled to an alternative urban politics? Here I tried to bring in some of your HC manifesto a bit to provide a more substantive critique before before leaving the conclusion a bit more open ended. Close by playing with the city metaphor, open circuits, and the Nam June Paik quote which ties everything together perfectly.

So moving forward I don't think you need to restructure much at all if you're onboard with how this flows. It's more about getting the transitions right so you can hit the points which are already there, ensuring your voice is consistent, and then tuning the more technical sections so they're clear and concise, doing what we can to keep the reader with us as we present the more substantive material.

**Comment by tchoi8** [comment]
these are great guideline to push the piece. its super helpful, and im returning to this frequently to figure out what and how to do things. thanks! more detailed response separately.

**Comment by hxrts** [comment]
closing this, moved all remaining points to google doc.
